version: '3.4'

services:
  crud.usermanagment.api:
    image: crudusermanagmentapi
    build:
      context: ../CRUD.UserManagement
      dockerfile: ./CRUD.UserManagement.API/Dockerfile
    ports:
      - "80"
      - "5000:80"
    depends_on:
      - mysql

  mysql:
    container_name: ${MYSQL_SERVER_NAME}
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - dbvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - secrets.env

  angular: # name of the first service
    build: "../CRUD.UserManagement.UI"
    volumes: # Volume binding
      - '../CRUD.UserManagement.UI:/usr/src/app' 
    ports:
      - "4200:4200" # specify port forewarding

volumes:
  dbvol: